networks:
  pytrix_network:
    name: pytrix_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  # Ambiente de Desenvolvimento (Apenas o core do Pytrix)
  pytrix:
    build:
      context: .
      dockerfile: pytrix_docker/Dockerfile.dev
    container_name: pytrix_dev_env
    restart: always
    env_file: .pytrix_env
    ports:
      - "${SSH_PORT:-2222}:22"
      - "3000:3000"
    networks:
      pytrix_network:
        ipv4_address: 172.20.0.10
    volumes:
      - .:/home/${DEV_USER:-developer}/pytrix
      - .ssh_cache:/home/${DEV_USER:-developer}/.ssh
    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash"]

  # Servidor de Arquivos Estáticos (Nginx)
  pytrix_web_static:
    image: nginx:alpine
    container_name: pytrix_static
    restart: always
    ports:
      - "8080:80"
    networks:
      pytrix_network:
        ipv4_address: 172.20.0.20
    volumes:
      - ./pytrix_web_static:/usr/share/nginx/html:ro




